### PR TITLE
The kit runtime is stored in .svelte-kit

### PR DESCRIPTION
**Pull request by twobitunicorn**

### CODE REVIEW

**Comment by johndunderhill** [comment]
Path seems wrong to me.  On my system the files are located in: .svelte-kit/runtime/app/
Am I missing something?

**Comment by twobitunicorn** [comment]
@johndunderhill Looks like that must have changed since this was commit pulled in.

**Comment by benmccann** [comment]
Here's a proposed solution: https://github.com/sveltejs/realworld/pull/103. Can you test it?

**Comment by johndunderhill** [comment]
@benmccann Looks great to me, thanks!

**Pull request merged**
